server {
    listen 80;
    server_name februandik.duckdns.org;

    root /var/www/februandik-web;
    index index.php index.html;

    access_log /var/log/nginx/februandik.access.log;
    error_log /var/log/nginx/februandik.error.log;

    client_max_body_size 10M;

    location / {
        try_files $uri $uri/ /app/index.php?$query_string;
    }

    location ~ \.php$ {
        include snippets/fastcgi-php.conf;
        fastcgi_pass unix:/run/php/php-fpm.sock;
    }

    location ^~ /storage/ {
        deny all;
        return 403;
    }

    location ^~ /deploy/ {
        deny all;
        return 403;
    }

    location ~ /\.(?:env|git|ht|gitignore)$ {
        deny all;
        return 403;
    }

    location ~* \.(?:jpg|jpeg|png|gif|webp|css|js|svg|ico)$ {
        try_files $uri =404;
        access_log off;
        expires 7d;
    }
}
